### PR TITLE
Update search_stat for Vim 8.1.1103

### PR DESCRIPTION
**Pull request by tjkirch**
Just context changes, except for addressing 8.1.0629, which added an end_pos
parameter to searchit.  Was able to build Vim OK afterward.

### CODE REVIEW

**Comment by tjkirch** [comment]
I have to admit I don't know how to test this, beyond the build, because I can't figure out how to use the feature itself.  I confirmed shortmess does not include "S", and did a search, but I don't see the count or "index" as described in the help.  I even reset my statusline to default to see if I was covering something, but I don't know where to look.

**Comment by chrisbra** [comment]
did you try with `vim --clean`

**Comment by tjkirch** [comment]
That did it.  I saw the search stat on the bottom right, near the line/column marker.  And since that helped me find it, I now also see it with my default configuration.  (It's in a separate bar, but same area.)

I apologize for my confusion!  In any case, consider this change tested now, and thanks! :)

**Comment by chrisbra** [comment]
okay, then I can merge this. Thanks!

**Pull request merged**
